ssh_config_file: /etc/ssh/sshd_config
pam_files:
  - /etc/pam.d/system-auth
  - /etc/pam.d/password-auth
pwquality_conf_file: /etc/security/pwquality.conf
system_auth_file: /etc/pam.d/system-auth
passwd_file_path: '/etc/passwd'
shadow_file_path: '/etc/shadow'
services_file_path: '/etc/services'
hosts_file_path: '/etc/hosts'
home_dirs_path: '/home'
login_defs_path: '/etc/login.defs'
max_days: 90
secure_permissions: 644
LAMP_type: 'Server(Linux)'
diag_file_path: '/home/ec2-user/Diag_File.txt'
get_path_1: grep PermitRootLogin {{ ssh_config_file }}
get_path_2_1: grep -E "minlen|minclass" {{ pwquality_conf_file }}
get_path_2_2: grep enforce_for_root {{ system_auth_file }}
get_path_3: grep -E 'pam_faillock.so' {{ item }} | grep deny || grep -E 'pam_faillock.so' {{ item }}
get_path_4: echo $PATH
get_path_5: 'find /etc /tmp /bin /sbin \( -nouser -o -nogroup \) -xdev -exec ls -l {} \\; 2>/dev/null'
get_path_9: 'cat {{ passwd_file_path }} | grep /home | cut -d: -f6'
get_path_10_1:  '|
    if [ -f /usr/sbin/ypserv ] && [ -f /usr/sbin/ypbind ] && [ -f /usr/sbin/ypxfrd ] && [ -f /usr/sbin/rpc.yppasswdd ] && [ -f /usr/sbin/rpc.yupdated ]; then
      echo "installed"
    fi'
get_path_10_2: ps -ef | grep -E "ypserv|ypbind|ypxfrd|rpc.yppasswdd|rpc.yupdated" | grep -v grep
get_path_11_1: cat /etc/mail/sendmail.cf | grep DZ | awk '{print $1}' | sed 's/DZ//g'
get_path_11_2: postconf -d | grep '^mail_version' | awk '{print $3}'
get_path_11_3: yum info postfix | grep Version | awk '{print $3}'
get_path_11_4: yum info sendmail | grep Version | awk '{print $3}'
get_path_12_1: ps -ef | grep named | grep -v grep
get_path_12_2: named -V
get_path_12_3: yum info bind | grep Version
get_path_15: grep '^PASS_MAX_DAYS' {{ login_defs_path }}

diag_file_value:
  - [1,'root 계정 원격 접속 제한','root 계정 telnet과 ssh 접속 제한 설정']
  - [2,'패스워드 복잡도 설정','패스워드 복잡도 설정 및 enforce_for_root 적용']
  - [3,'계정 잠금 임계값 설정','계정 임계값 5회 이하로 설정']
  - [4,'root 홈, 디렉터리 소유자 설정','root 계정의 설정 파일에서 PATH=$PATH:$HOME/bin으로 수정']
  - [5,'파일 및 디렉터리 소유자 설정','소유자가 존재하지 않는 파일이나 디렉터리가 불필요한 경우 rm 명령으로 삭제']
  - [6,'/etc/passwd 파일 소유자 및 권한 설정','/etc/passwd 파일 소유자 및 권한 변경']
  - [7,'/etc/shadow 파일 소유자 및 권한 설정','/etc/shadow 파일 소유자 및 권한 변경']
  - [8,'/etc/services 파일 소유자 및 권한 설정','/etc/services 파일의 퍼미션을 644로, 소유자를 root로 변경']
  - [9,'사용자, 시스템 시작파일, 환경파일 소유자 및 권한 설정','소유자 변경 및 일반 사용자 쓰기 권한 제거']
  - [10,'NIS, NIS+ 점검','NFS 서비스 데몬 중지']
  - [11,'Sendmail 버전 점검','Sendmail, postfix 서비스 실행 여부 및 버전 점검 후, OS 벤더사의 보안 패치 설치']
  - [12,'DNS 보안 버전 패치','최신 보안 패치 적용 혹은 DNS 데몬 중지']
  - [13,'/etc/hosts 파일 소유자 및 권한 설정','/etc/hosts 파일 접근 권한 644, 소유자 root로 변경']
  - [14,'cron 파일 소유자 및 권한 설정','chown root 혹은 chmod 640으로 파일 소유자 및 권한 변경']
  - [15,'패스워드 최대 사용 기간 설정','패스워드 최대 사용 기간 90일 이하로 설정']
