#Server(Linux): root 홈, 디렉터리 소유자 설정
---
- name: Linux(server) 4
  hosts: aws_web
  vars:
    diag_file_path: '/home/ec2-user/Diag_File.csv'  # 진단 결과 파일 경로
    LAMP_type: 'Server(Linux)'  # LAMP

  tasks:
  - name: Get PATH
    shell: echo $PATH
    register: path
    changed_when: false

  - name: Print path
    debug:
      msg: "{{ path }}"

  - name: Split path
    set_fact:
      path_list: "{{ path.stdout.split(':') }}"

  - name: Print path_list
    debug:
      msg: "{{ path_list | join('   ') }}"

  - name: Filter path_list
    set_fact:
      filter_path_list: "{{ path_list[:-1] }}"

  - name: Print filter_path_list
    debug:
      msg: "{{ filter_path_list | join('   ') }}"
  
  - name: Check .
    set_fact:
      has_dot: "{{ '.' in filter_path_list }}"

  - name: Write secure diagnostic result to file
    set_fact:
      diag_result: "S"
    when: not has_dot


  - name: Write vulnerable diagnostic result to file
    set_fact:
      diag_result: "V"
    when: has_dot

  - name: Write diagnostic result to file
    lineinfile:
      path: "{{ diag_file_path }}"
      line: "{{ LAMP_type }}, 'root 홈, 디렉터리 소유자 설정', {{ diag_result }}, root 계정의 설정 파일에서 PATH=$PATH:$HOME/bin으로 수정"
      create: yes