# Apache: 파일 업로드 및 다운로드 제한
---
- name: Check and set file upload/download limit in Apache
  hosts: aws_web
  become: yes
  vars:
    apache_config_path: '/etc/httpd/conf/httpd.conf'  # Apache 설정 파일 경로
    diag_file_path: '/home/ec2-user/Diag_File.txt'  # 진단 결과 파일 경로
    diagnostic_number: 4  # 진단 항목 번호

  tasks:
    - name: Check if LimitRequestBody is set in httpd.conf
      command: "grep LimitRequestBody {{ apache_config_path }}"
      register: limit_request_body
      ignore_errors: true

    - name: Display vulnerability status
      set_fact:
        diag_result: "V" 
      when: limit_request_body.rc != 0

    - name: Display secure status
      set_fact:
        diag_result: "S" 
      when: limit_request_body.rc == 0

    - name: Write diagnostic result to file
      lineinfile:
        path: "{{ diag_file_path }}"
        line: "{{ diagnostic_number }}, 파일 업로드 및 다운로드 제한, {{ diag_result }}"
        create: yes