#Server(Linux): root 계정 원격 접속 제한
---
- name: root 계정 원격 접속 제한 점검
  hosts: aws_web
  become: yes
  vars:
    ssh_config_file: /etc/ssh/sshd_config  # SSH 설정 파일 경로 변수화
    diag_file_path: '/home/ec2-user/Diag_File.txt'  # 진단 결과 파일 경로
    LAMP_type: 'Server(Linux)'  # LAMP

  tasks:
    - name: Check SSH root login setting
      command: grep PermitRootLogin {{ ssh_config_file }}
      register: ssh_check
      changed_when: false

    - name: PermitRootLogin 설정 확인 (양호)
      set_fact:
        diag_result: "S"
      when: "'PermitRootLogin no' in ssh_check.stdout"

    - name: PermitRootLogin 설정 확인 (취약)
      set_fact:
        diag_result: "V"
      when: "'PermitRootLogin no' not in ssh_check.stdout"

    - name: Write diagnostic result to file
      lineinfile:
        path: "{{ diag_file_path }}"
        line: "{{ LAMP_type }}, root 계정 원격 접속 제한, {{ diag_result }}, root 계정 telnet과 ssh 접속 제한 설정"
        create: yes