---
- name: Check for latest PHP security patches
  hosts: localhost
  tasks:
    - name: Check for upgradable PHP packages
      command: apt list --upgradable  # Ubuntu: apt list --upgradable
                                      # CentOS: dnf check-update
      register: upgrade_check

    - name: Filter PHP packages
      set_fact:
        php_upgradable: "{{ upgrade_check.stdout_lines | select('search', 'php') | list }}"

    - name: Fail if PHP packages need upgrade
      debug:
        msg: "Vulnerability detected: PHP needs an upgrade. It's not the latest."
      when: php_upgradable | length != 0

    - name: Skip if PHP is latest
      debug:
        msg: "ok. No action needed because PHP is the latest."
      when: php_upgradable | length == 0

