# PHP 실행 경로 제한
---
- name: Check PHP open_basedir setting
  hosts: localhost
  vars_files:
    - ./php_path.yml
  tasks:
    - name: Check open_basedir in php.ini
      command: grep open_basedir {{ custom_path }}
      register: open_basedir_check

    - name: Set open_basedir result if available
      set_fact:
        open_basedir_result: "{{ open_basedir_check.stdout_lines[1] | default('') }}"
      when: open_basedir_check.stdout_lines | length > 1

    - name: Set value after equals if open_basedir_result is set
      set_fact:
        value_after_equals: "{{ open_basedir_result.split('=')[1] | trim }}"
      when: open_basedir_result | length > 0 

    - name: Fail if open_basedir is empty
      debug:
        msg: "Vulnerability detected: open_basedir is empty."
      when: value_after_equals | default('') == ''

    - name: Skip if open_basedir is not empty
      debug:
        msg: "ok. No action needed because it's not empty."
      when: value_after_equals | default('') != ''

