# 불필요한 명령어 사용 제한
---
- name: Check PHP display_functions setting
  hosts: localhost
  vars_files: 
    - ./php_path.yml
  tasks:
    - name: Check disable_functions in php.ini
      command: grep disable_functions {{ custom_path }}
      register: disable_functions_check
      ignore_errors: yes

    - name: Set disable_functions result
      set_fact:
        disable_functions_result: "{{ disable_functions_check.stdout | trim}}"

    - name: fail if disable_functions is set 
      debug:
        msg: "Vulnerability detected: disable_functions is empty."
      when: disable_functions_check.stdout is search('disable_functions =\\s*$')

    - name: Skip if disable_functions is set to Off
      debug:
        msg: "ok. disable_functions is not empty. No action needed."
      when: disable_functions_check.stdout is not search('disable_functions =\\s*$')

