# Mysql: "불필요한 계정 제거"
---
- name: Mysql_1
  hosts: aws_db
  vars:
    login_user: 'root'
    login_password: 'guseodhxhdpqj2@'
    login_db: 'mysql'
    login_host: localhost
    query: "SELECT host, user, authentication_string FROM user"
    regi_users_1: ['test']

  tasks:
  - name: Run Query
    mysql_query:
      login_user: "{{ login_user }}"
      login_password: "{{ login_password }}"
      login_host: "{{ login_host }}"
      login_db: "{{ login_db }}"
      query: "{{ query }}"
    register: query_result

  - name: Print query_result
    debug:
      var: query_result

  - name: Filter User
    set_fact:
      users: "{{ query_result.query_result[0] | map(attribute='user') | list }}"

  - name: Print users
    debug:
      var: users
  
  - name: Print regi_users_1
    debug:
      var: regi_users_1

  - name: Check unregi users
    set_fact:
      unregi_users: "{{ users | difference(regi_users_1) }}"

  - name: Print unregi_users
    debug:
      var: unregi_users

  - name: Check
    debug:
      msg: "{{ 'good' if (unregi_users | length == 0) else 'bad' }}"
