# Mysql: "사용자 계정 정보 테이블 접근 권한"
---
- name: Mysql_4
  hosts: aws_db
  vars:
    login_user: 'root'
    login_password: 'guseodhxhdpqj2@'
    login_db: 'mysql'
    login_host: localhost
    query: "SELECT host, user, select_priv FROM mysql.user;"
    regi_users_4: ['root', 'mysql']
    Select_priv: 'select_priv'

  tasks:
  - name: Run Query
    mysql_query:
      login_user: "{{ login_user }}"
      login_password: "{{ login_password }}"
      login_host: "{{ login_host }}"
      query: "{{ query }}"
    register: query_result

  - name: Print query_result
    debug:
      var: query_result
  
  - name: Filter 'Y' User
    set_fact:
      priv_users: "{{ query_result.query_result[0] | selectattr(Select_priv, 'equalto', 'Y') | map(attribute='user') | list }}"

  - name: Print priv_users
    debug:
      var: priv_users

  - name: Print regi_users_4
    debug:
      var: regi_users_4

  - name: Check unregi users
    set_fact:
      unregi_users: "{{ priv_users | difference(regi_users_4) }}"

  - name: Print unregi_users
    debug:
      var: unregi_users

  - name: Check
    debug:
      msg: "{{ 'good' if (unregi_users | length == 0) else 'bad' }}"
