# Apache: 불필요한 파일 제거
---
- name: Check and remove unnecessary Apache manual files
  hosts: aws_web
  become: yes
  vars:
    apache_config_path: '/etc/httpd'  # Apache 설정 디렉토리 경로
    diag_file_path: '/home/ec2-user/Diag_File.txt'  # 진단 결과 파일 경로
    diagnostic_number: 2  # 진단 항목 번호

  tasks:
    - name: Check if the manual directory exists
      command: "find {{ apache_config_path }} -name manual"
      register: manual_dir_check
      ignore_errors: yes

    - name: Check for manual settings in httpd.conf
      command: "grep -i 'manual' {{ apache_config_path }}/conf/httpd.conf"
      register: manual_setting_check
      ignore_errors: yes

    - name: Diag_result is secure
      set_fact:
        diag_result: "S" 
      when: manual_dir_check.stdout | length == 0 and manual_setting_check.stdout | length == 0

    - name: Diag_result is vulnerable
      set_fact:
        diag_result: "V"
      when: not (manual_dir_check.stdout | length == 0 and manual_setting_check.stdout | length == 0)

    - name: Write diagnostic result to file
      lineinfile:
        path: "{{ diag_file_path }}"
        line: "{{ diagnostic_number }}, 불필요한 파일 제거, {{ diag_result }}"
        create: yes
