# Apache: 최신 보안 패치 적용
---
- name: Check Apache version for security patches
  hosts: aws_web
  tasks:
    - name: Check current Apache version
      command: httpd -v
      register: current_apache_version
      changed_when: false

    - name: Check latest available Apache version
      command: yum info httpd | Version
      register: latest_apache_info

    - name: Extract the latest Apache version
      set_fact:
        latest_version: "{{ latest_apache_info.stdout | regex_search('([0-9]+\\.[0-9]+\\.[0-9]+)') }}"

    - name: Extract the current Apache version
      set_fact:
        current_version: "{{ current_apache_version.stdout | regex_search('([0-9]+\\.[0-9]+\\.[0-9]+)') }}"

    - name: Fail if current version extraction fails
      fail:
        msg: "Failed to extract the current Apache version. Output was: {{ current_apache_version.stdout }}"
      when: current_version is none

    - name: Fail if latest version extraction fails
      fail:
        msg: "Failed to extract the latest Apache version. Output was: {{ latest_apache_info.stdout }}"
      when: latest_version is none

    - name: Convert versions to strings
      set_fact:
        current_version_str: "{{ current_version | string }}"
        latest_version_str: "{{ latest_version | string }}"

    - name: Debug current and latest versions
      debug:
        msg: "Current version: {{ current_version_str }}, Latest version: {{ latest_version_str }}"

    - name: Compare versions and determine vulnerability status
      debug:
        msg: "Vulnerable: The installed version of Apache is outdated. Please update."
      when: current_version_str is version(latest_version_str, '<')

    - name: Display secure status
      debug:
        msg: "Secure: The installed version of Apache is up to date."
      when: current_version_str is not version(latest_version_str, '<')




