# Apache: 디렉터리 리스팅 제거
---
- name: Check directory listing settings in Apache
  hosts: aws_web
  become: yes 
  vars:
    apache_config_path: '/etc/httpd/'  # Apache 설정 디렉토리 경로
    diag_file_path: '/home/ec2-user/Diag_File.csv'  # 진단 결과 파일 경로
    LAMP_type: 'Apache'  # LAMP

  tasks:

    - name: Check if Indexes option is set in Apache configuration
      command: "grep -r 'Indexes' {{ apache_config_path }}conf/httpd.conf"
      register: index_option
      ignore_errors: true

    - name: Display vulnerability status
      set_fact:
        diag_result: "V"
      when: index_option.rc == 0

    - name: Display secure status
      set_fact:
        diag_result: "S"
      when: index_option.rc != 0

    - name: Write diagnostic result to file
      lineinfile:
        path: "{{ diag_file_path }}"
        line: "{{ LAMP_type }}, 디렉터리 리스팅 제거, {{ diag_result }}, 디렉터리 검색 기능 제거"
        create: yes