# Apache: 파일 업로드 및 다운로드 제한
---
- name: Check and set file upload/download limit in Apache
  hosts: aws
  become: yes
  vars:
    apache_config_path: '/etc/httpd/conf/httpd.conf'  # Apache 설정 파일 경로

  tasks:
    - name: Check if LimitRequestBody is set in httpd.conf
      command: "grep LimitRequestBody {{ apache_config_path }}"
      register: limit_request_body
      ignore_errors: true

    - name: Display vulnerability status
      debug:
        msg: "Vulnerable: No file upload and download size limit is set."
      when: limit_request_body.rc != 0

    - name: Display secure status
      debug:
        msg: "Secure: File upload and download size limits are set."
      when: limit_request_body.rc == 0
