#Server(Linux): 패스워드 최대 사용 기간 설정
---
- name: Check password maximum age settings
  hosts: aws_web
  become: yes
  vars:
    login_defs_path: '/etc/login.defs'  # 로그인 설정 파일 경로
    max_days: 90  # 최대 사용 기간 기준일
    diag_file_path: '/home/ec2-user/Diag_File.txt'  # 진단 결과 파일 경로
    LAMP_type: 'Server(Linux)'  # LAMP

  tasks:
    - name: Check PASS_MAX_DAYS in /etc/login.defs
      command: "grep '^PASS_MAX_DAYS' {{ login_defs_path }}"
      register: max_days_info
      changed_when: false

    - name: Set fact for PASS_MAX_DAYS value
      set_fact:
        pass_max_days: "{{ max_days_info.stdout.split()[1] | int }}"

    - name: Check if PASS_MAX_DAYS is within the acceptable range
      set_fact:
        diag_result: "S"
      when: pass_max_days | int <= max_days

    - name: Check if PASS_MAX_DAYS is vulnerable
      set_fact:
        diag_result: "V"
      when: pass_max_days | int > max_days

    - name: Write diagnostic result to file
      lineinfile:
        path: "{{ diag_file_path }}"
        line: "{{ LAMP_type }}, 패스워드 최대 사용 기간 설정, {{ diag_result }}, 패스워드 최대 사용 기간 90일 이하로 설정"
        create: yes
