# Linux Server: /etc/services 파일 소유자 및 권한 설정
---
- name: Check /etc/services file ownership and permissions
  hosts: localhost  # 변경할 호스트 그룹
  become: yes  # sudo 권한 사용
  vars:
    services_file_path: '/etc/services'  # 검사할 파일 경로

  tasks:
    - name: Check ownership and permissions of /etc/services
      stat:
        path: "{{ services_file_path }}"
      register: services_file_info

    - name: Display current permissions in octal
      debug:
        msg: "Current permissions for /etc/services: {{ services_file_info.stat.mode | int }}"

    - name: Check if /etc/services is secure
      debug:
        msg: "Secure: /etc/services is owned by root and permissions are 644 or lower."
      when: services_file_info.stat.pw_name == 'root' and services_file_info.stat.mode | int <= 644

    - name: Check if /etc/services is vulnerable
      debug:
        msg: "Vulnerable: /etc/services is either not owned by root or permissions are greater than 644."
      when: services_file_info.stat.pw_name != 'root' or services_file_info.stat.mode | int > 644
