# Apache: 불필요한 파일 제거
---
- name: Check and remove unnecessary Apache manual files
  hosts: aws_web
  become: yes
  vars:
    apache_config_path: '/etc/httpd'  # Apache 설정 디렉토리 경로

  tasks:
    - name: Check if the manual directory exists
      command: "find {{ apache_config_path }} -name manual"
      register: manual_dir_check
      ignore_errors: yes

    - name: Check for manual settings in httpd.conf
      command: "grep -i 'manual' {{ apache_config_path }}/conf/httpd.conf"
      register: manual_setting_check
      ignore_errors: yes

    - name: Display status for unnecessary manual files and directories
      debug:
        msg: >
          {% if manual_dir_check.stdout | length == 0 and manual_setting_check.stdout | length == 0 %}
          Secure: Manual files and directories have been removed.
          {% else %}
          Vulnerable: Manual files and/or directories exist.
          {% endif %}
