#Server(Linux): 사용자, 시스템 시작파일, 환경파일 소유자 및 권한 설정
---
- name: Check user and environment file ownership and permissions
  hosts: aws_web
  become: yes
  vars:
    home_dirs_path: '/home'  # 홈 디렉터리 경로
    passwd_file_path: '/etc/passwd'  # 사용자 정보 파일 경로
    secure_permissions: 644  # 허용할 최대 권한
    diag_file_path: '/home/ec2-user/Diag_File.txt'  # 진단 결과 파일 경로
    LAMP_type: 'Server(Linux)'  # LAMP

  tasks:
    - name: Get a list of user home directories
      shell: "cat {{ passwd_file_path }} | grep /home | cut -d: -f6"
      register: home_dirs

    - name: Check ownership and permissions for each home directory
      stat:
        path: "{{ item }}"
      register: dir_info
      loop: "{{ home_dirs.stdout_lines }}"

    - name: Check permissions and display vulnerable status
      set_fact:
        diag_result: "V"
      when: item.stat.pw_name is not defined or item.stat.pw_name != 'root' or item.stat.mode | int > secure_permissions
      loop: "{{ dir_info.results }}"

    - name: Check permissions and display secure status
      set_fact:
        diag_result: "S"
      when: item.stat.pw_name is defined and item.stat.pw_name == 'root' and item.stat.mode | int <= secure_permissions
      loop: "{{ dir_info.results }}"

    - name: Write diagnostic result to file
      lineinfile:
        path: "{{ diag_file_path }}"
        line: "{{ LAMP_type }}, '사용자, 시스템 시작파일, 환경파일 소유자 및 권한 설정', {{ diag_result }}, 소유자 변경 및 일반 사용자 쓰기 권한 제거"
        create: yes