#Server(Linux): 파일 및 디렉터리 소유자 설정
---
- name: 파일 및 디렉터리 소유자 설정 점검
  hosts: aws_web
  become: yes
  vars:
    diag_file_path: '/home/ec2-user/Diag_File.csv'  # 진단 결과 파일 경로
    LAMP_type: 'Server(Linux)'  # LAMP

  tasks:
    - name: Find files and directories without valid owner or group
      shell: "find /etc /tmp /bin /sbin \\( -nouser -o -nogroup \\) -xdev -exec ls -l {} \\; 2>/dev/null"
      register: invalid_files
      changed_when: false

    - name: Display '취약' if invalid files or directories are found
      set_fact:
        diag_result: "V"
      when: invalid_files.stdout != ""

    - name: Display '양호' if no invalid files or directories are found
      set_fact:
        diag_result: "S"
      when: invalid_files.stdout == ""

    - name: Write diagnostic result to file
      lineinfile:
        path: "{{ diag_file_path }}"
        line: "{{ LAMP_type }}, 파일 및 디렉터리 소유자 설정, {{ diag_result }}, 소유자가 존재하지 않는 파일이나 디렉터리가 불필요한 경우 rm 명령으로 삭제"
        create: yes