# Mysql: "root 권한으로 서버 구동 제한"
---
- name: Mysql_5
  hosts: internetweb

  tasks:
  - name: Get mysqld process
    shell: ps -ef | grep maria | grep -v grep
    register: mysqld_process
    changed_when: false

  - name: Print mysqld_process
    debug:
      var: mysqld_process.stdout_lines

  - name: Extract user running mysqld
    set_fact:
      mysqld_user: "{{ mysqld_process.stdout_lines[0].split()[0] }}"

  - name: Print mysqld user
    debug:
      var: mysqld_user

  - name: Check
    debug:
      msg: "{{ 'bad' if mysqld_user == 'root' else 'good' }}"
