# Mysql: "로그 활성화"
---
- name: Mysql_8
  hosts: internetweb
  vars:
    login_user: 'test'
    login_password: '1234'
    login_db: 'mysql'
    login_host: localhost
    query_general: "SHOW VARIABLES LIKE 'general_log%';"
    query_slow: "SHOW VARIABLES LIKE 'slow%';"

  tasks:
  - name: Run Query_general
    mysql_query:
      login_user: "{{ login_user }}"
      login_password: "{{ login_password }}"
      login_host: "{{ login_host }}"
      login_db: "{{ login_db }}"
      query: "{{ query_general }}"
    register: query_general_result

  - name: Print query_general_result
    debug:
      var: query_general_result

  - name: Run slow Query
    mysql_query:
      login_user: "{{ login_user }}"
      login_password: "{{ login_password }}"
      login_host: "{{ login_host }}"
      login_db: "{{ login_db }}"
      query: "{{ query_slow }}"
    register: query_slow_result

  - name: Print query_slow_result
    debug:
      var: query_slow_result

  - name: Filter general log value
    set_fact:
      general_log_value: "{{ query_general_result.query_result[0] | selectattr('Variable_name', 'equalto', 'general_log') | map(attribute='Value') | first }}"

  - name: Print general_log_value
    debug:
      var: general_log_value
  
  - name: Filter slow query log value
    set_fact:
      slow_log_value: "{{ query_slow_result.query_result[0] | selectattr('Variable_name', 'equalto', 'slow_query_log') | map(attribute='Value') | first }}"

  - name: Print slow_log_value
    debug:
      var: slow_log_value

  - name: Check good
    debug:
      msg: "good"
    when: slow_log_value == 'ON'

  - name: Check bad
    debug:
      msg: "bad"
    when: slow_log_value != 'ON'
