#Linux(server): root 계정 원격 접속 제한
---
- name: root 계정 원격 접속 제한 점검
  hosts: all
  become: yes
  vars:
    ssh_config_file: /etc/ssh/sshd_config  # SSH 설정 파일 경로 변수화

  tasks:
    - name: Check SSH root login setting
      command: grep PermitRootLogin {{ ssh_config_file }}
      register: ssh_check
      changed_when: false

    - name: PermitRootLogin 설정 확인
      debug:
        msg: >
          {{
            '양호' if 'PermitRootLogin no' in ssh_check.stdout else '취약'
          }}

