#Server(Linux): /etc/services 파일 소유자 및 권한 설정
---
- name: Check /etc/services file ownership and permissions
  hosts: aws_web
  become: yes
  vars:
    services_file_path: '/etc/services'  # 검사할 파일 경로
    diag_file_path: '/home/ec2-user/Diag_File.csv'  # 진단 결과 파일 경로
    LAMP_type: 'Server(Linux)'  # LAMP

  tasks:
    - name: Check ownership and permissions of /etc/services
      stat:
        path: "{{ services_file_path }}"
      register: services_file_info

    - name: Display current permissions in octal
      debug:
        msg: "Current permissions for /etc/services: {{ services_file_info.stat.mode | int }}"

    - name: Check if /etc/services is secure
      set_fact:
        diag_result: "S"
      when: services_file_info.stat.pw_name == 'root' and services_file_info.stat.mode | int <= 644

    - name: Check if /etc/services is vulnerable
      set_fact:
        diag_result: "V"
      when: services_file_info.stat.pw_name != 'root' or services_file_info.stat.mode | int > 644

    - name: Write diagnostic result to file
      lineinfile:
        path: "{{ diag_file_path }}"
        line: "{{ LAMP_type }}, /etc/services 파일 소유자 및 권한 설정, {{ diag_result }}, '/etc/services 파일의 퍼미션을 644로, 소유자를 root로 변경'"
        create: yes