---
- name: Compare Mysql version with RPM package version
  hosts: aws_db
  vars:
    login_user: 'root'
    login_password: 'guseodhxhdpqj2@'
    login_db: 'mysql'
    login_host: localhost
    query: "SELECT @@version;"
  
  tasks:
  - name: Run Query
    mysql_query:
      login_user: "{{ login_user }}"
      login_password: "{{ login_password }}"
      login_db: "{{ login_db }}"
      login_host: "{{ login_host }}"
      query: "{{ query }}"
    register: query_result

  - name: Print query_result
    debug:
      var: query_result

  - name: Parse Mysql version
    set_fact:
      mysql_version: "{{ query_result.query_result[0][0]['@@version'] }}"
  
  - name: Print db_version
    debug:
      var: mysql_version

  - name: Get installed mysql-server package version
    shell: docker exec -it mysql-server rpm -qa | grep mysql
    register: rpm_version_output
    changed_when: false

  - name: Print version
    debug:
      var: rpm_version_output

  - name: Parse RPM version
    set_fact:
      rpm_version: "{{ rpm_version_output.stdout_lines[0].split('-')[4] }}"

  - name: Print rpm_version
    debug:
      var: rpm_version

  - name: Check bad
    debug:
      msg: "bad"
    when: mysql_version is version(rpm_version, '<')

  - name: Check good
    debug:
      msg: "good"
    when: mysql_version is not version(rpm_version, '<')
