#Server(Linux): /etc/hosts 파일 소유자 및 권한 설정
---
- name: Check /etc/hosts file ownership and permissions
  hosts: aws_web
  become: yes
  vars:
    hosts_file_path: '/etc/hosts'  # 검사할 파일 경로
    diag_file_path: '/home/ec2-user/Diag_File.txt'  # 진단 결과 파일 경로
    LAMP_type: 'Server(Linux)'  # LAMP

  tasks:
    - name: Check ownership and permissions of /etc/hosts
      stat:
        path: "{{ hosts_file_path }}"
      register: hosts_file_info

    - name: Display current permissions in octal
      debug:
        msg: "Current permissions for /etc/hosts: {{ hosts_file_info.stat.mode | int }}"

    - name: Check if /etc/hosts is secure
      set_fact:
        diag_result: "S"
      when: hosts_file_info.stat.pw_name == 'root' and hosts_file_info.stat.mode | int <= 644

    - name: Check if /etc/hosts is vulnerable
      set_fact:
        diag_result: "V"
      when: hosts_file_info.stat.pw_name != 'root' or hosts_file_info.stat.mode | int > 644

    - name: Write diagnostic result to file
      lineinfile:
        path: "{{ diag_file_path }}"
        line: "{{ LAMP_type }}, /etc/hosts 파일 소유자 및 권한 설정, {{ diag_result }}, '/etc/hosts 파일 접근 권한 644, 소유자 root로 변경'"
        create: yes