# Mysql: "타 사용자에 권한 부여 옵션 제한"
---
- name: Mysql_3
  hosts: internetweb
  vars:
    login_user: 'test'
    login_password: '1234'
    login_db: 'mysql'
    login_host: localhost
    query: "SELECT host, user, Grant_priv FROM user WHERE Grant_priv='Y';"
    regi_users_3: ['mysql', 'root']
    Grant_priv: 'Grant_priv'

  tasks:
  - name: Run Query
    mysql_query:
      login_user: "{{ login_user }}"
      login_password: "{{ login_password }}"
      login_host: "{{ login_host }}"
      login_db: "{{ login_db }}"
      query: "{{ query }}"
    register: query_result

  - name: Print query_result
    debug:
      var: query_result

  - name: Filter 'Y' User
    set_fact:
      priv_users: "{{ query_result.query_result[0] | selectattr(Grant_priv, 'equalto', 'Y') | map(attribute='User') | list }}"

  - name: Print priv_users
    debug:
      var: priv_users

  - name: Print regi_users_3
    debug:
      var: regi_users_3

  - name: Check unregi users
    set_fact:
      unregi_users_3: "{{ priv_users | difference(regi_users_3) }}"

  - name: Print unregi_users
    debug:
      var: unregi_users_3

  - name: Check
    debug:
      msg: "{{ 'good' if (unregi_users_3 | length == 0) else 'bad' }}"
