# Apache: 링크 사용 금지
---
- name: Check for symbolic links and alias restrictions in Apache
  hosts: aws_web
  become: yes
  vars:
    apache_config_path: '/etc/httpd/conf/httpd.conf'  # Apache 설정 파일 경로
    alias_config_path: '/etc/httpd/conf/httpd.conf'  # Alias 설정 파일 경로


  tasks:
    - name: Check if FollowSymLinks is enabled
      command: "grep FollowSymLinks {{ apache_config_path }}"
      register: follow_symlinks_check
      ignore_errors: yes

    - name: Check for aliases in Apache configuration
      command: "grep '^Alias' {{ alias_config_path }}"
      register: alias_check
      ignore_errors: yes

    - name: Display status for FollowSymLinks
      debug:
        msg: >
          {% if follow_symlinks_check.stdout is search('Indexes') %}
          Vulnerable: FollowSymLinks is enabled.
          {% else %}
          Secure: FollowSymLinks is not enabled.
          {% endif %}

    - name: Display status for aliases
      debug:
        msg: >
          {% if alias_check.stdout | length > 0 %}
          Vulnerable: Aliases are configured and not commented out.
          {% else %}
          Secure: No aliases are configured or they are commented out.
          {% endif %}
