---
- name: Check PHP display_errors setting
  hosts: localhost
  vars_files:
    - ./php_path.yml
  tasks:
    - name: Check display_errors in php.ini
      command: grep display_errors {{ custom_path }}
      register: display_errors_check
      ignore_errors: yes

    - name: Fail if display_errors is set to On
      debug:
        msg: "Vulnerability detected: display_errors is set to 'On'."
      when: display_errors_check.stdout is search('display_errors\s*=\s*On')

    - name: Skip if display_errors is set to Off
      debug:
        msg: "ok. display_errors is set to 'Off'. No action needed."
      when: display_errors_check.stdout is search('display_errors\s*=\s*Off')

