# Apache: 웹 프로세스 권한 제한
---
- name: Check Apache process owner and permissions
  hosts: aws_web
  gather_facts: no
  vars:
    diag_file_path: '/home/ec2-user/Diag_File.txt'  # 진단 결과 파일 경로
    diagnostic_number: 6  # 진단 항목 번호

  tasks:
    - name: Check if Apache is running
      shell: ps -ef | grep apache2
      register: apache_process
      changed_when: false

    - name: Set fact for Apache process status
      set_fact:
        apache_owner: "{{ item.split()[0] }}"
        diag_result: "S"
      loop: "{{ apache_process.stdout_lines }}"
      when: item.split()[0] != "root"

    - name: Output secure status
      debug:
        msg: "Apache is running with non-root user: {{ apache_owner }}"
      when: diag_result == "S"

    - name: Set fact for vulnerable status
      set_fact:
        apache_owner: "{{ item.split()[0] }}"
        diag_result: "V"
      loop: "{{ apache_process.stdout_lines }}"
      when: item.split()[0] == "root"

    - name: Output vulnerable status
      debug:
        msg: "Apache is running with root user: {{ apache_owner }}"
      when: diag_result == "V"

    - name: Write diagnostic result to file
      lineinfile:
        path: "{{ diag_file_path }}"
        line: "{{ diagnostic_number }}, 웹 프로세스 권한 제한, {{ diag_result }}"
        create: yes