# Mysql: "환경설정 파일 접근 권한"
---
- name: Mysql_6
  hosts: aws_db
  vars:
    path: /etc/my.cnf.d/mariadb-server.cnf

  tasks:
  - name: Get perm
    shell: docker exec -it mysql-server ls -alL /etc/my.cnf
    register: perm
    changed_when: false

  - name: Print perm
    debug:
      var: perm

  - name: Parsing perm
    set_fact:
      file_perm: "{{ perm.stdout_lines[0].split()[0] }}"

  - name: Print file_perm
    debug:
      var: file_perm

  - name: Convert file_perm
    set_fact:
      num_perm: >-
          {{
            (((4 * (file_perm[1] == 'r') | int) +
             (2 * (file_perm[2] == 'w') | int) +
             (1 * (file_perm[3] == 'x') | int)) * 64) +
            (((4 * (file_perm[4] == 'r') | int) +
             (2 * (file_perm[5] == 'w') | int) +
             (1 * (file_perm[6] == 'x') | int)) * 8) +
            ((4 * (file_perm[7] == 'r') | int) +
             (2 * (file_perm[8] == 'w') | int) +
             (1 * (file_perm[9] == 'x') | int))
          }}

  - name: octal_perm
    set_fact:
      octal_perm: "{{ '%o' | format(num_perm | int) }}"

  - name: Print octal_perm
    debug:
      var: octal_perm

  - name: Determine
    set_fact:
      status: "{{ 'good' if octal_perm | int <= 640 else 'bad' }}"

  - name: Print status
    debug:
      var: status
