---
- name: Check PHP expose_php setting
  hosts: localhost
  tasks:
    - name: Check expose_php in php.ini
      command: grep expose_php /etc/php/8.3/cli/php.ini
      register: expose_php_check
      ignore_errors: yes

    - name: Set expose_php result
      set_fact:
        expose_php_result: "{{ expose_php_check.stdout | trim }}" 
    - name:
      debug:
        msg: "{{ expose_php_result}}"


    - name: fail if expose_php is set to On
      debug:
        msg: "Warning - Vulnerability detected: expose_php is set to 'On'."
      when: expose_php_check.stdout is search('expose_php\s*=\s*On')

    - name: Skip if expose_php is set to Off
      debug:
        msg: "expose_php is set to 'Off'. No action needed."
      when: expose_php_check.stdout is search('expose_php\s*=\s*Off')

