---
- name: Security Checks_Web
  hosts: aws_web, aws_server2, ubuntu
  pre_tasks:
    - include_tasks: roles/linux_security_checks/pre_tasks.yml
 
  roles:
    - linux_security_checks
  tasks:
    - name: Intergration Testing
      include_tasks: roles/linux_security_checks/tests/Testing_intergration.yml
