---
- name: Security Checks_DB
  #hosts: aws_db
  hosts: aws_server2
  pre_tasks:
    - include_tasks: pre_tasks.yml
  roles:
    - mysql_security_checks

- name: Security Checks_Web
  hosts: aws_web
  roles:
    - apache_security_checks
    - php_security_checks
    - linux_security_checks
