---
- name: Security Checks_DB
  #hosts: aws_db, aws_server2
  hosts: ubuntu
  pre_tasks:
    - include_tasks: pre_tasks.yml
  roles:
    - mysql_security_checks
  tasks:
    - name: Intergration Testing
      import_tasks: roles/mysql_security_checks/tests/Testing_intergration.yml

- name: Security Checks_Web
  hosts: aws_web
  roles:
    - apache_security_checks
    - php_security_checks
    - linux_security_checks
