# Apache: 웹 서비스 영역의 분리
---
- name: Check and update Apache DocumentRoot
  hosts: intranetweb  # 변경할 호스트 그룹
  become: yes  # sudo 권한 사용
  vars:
    apache_config_path: '/etc/apache2/sites-available/000-default.conf'  # Apache 설정 파일 경로
    secure_directory_path: '/var/secure/mysecurepath'  # 안전한 경로
    default_document_root: '/var/www/html'  # 기본 DocumentRoot 경로

  tasks:
    - name: Ensure Apache is installed
      apt:
        name: apache2
        state: present

    - name: Check current DocumentRoot
      command: "grep DocumentRoot {{ apache_config_path }}"
      register: document_root_check
      ignore_errors: yes

    - name: Display current DocumentRoot
      debug:
        msg: "Current DocumentRoot is: {{ document_root_check.stdout }}"

    - name: Check if DocumentRoot is vulnerable
      debug:
        msg: "Vulnerable: Default DocumentRoot is being used."
      when: document_root_check.stdout is search('htdocs') or document_root_check.stdout is search(default_document_root)

    - name: Check if DocumentRoot is secure
      debug:
        msg: "Secure: Default DocumentRoot is not being used."
      when: not (document_root_check.stdout is search('htdocs') or document_root_check.stdout is search(default_document_root))

    - name: Create secure directory
      file:
        path: "{{ secure_directory_path }}"  # 안전한 경로
        state: directory
        mode: '0755'  # 권한 설정

    - name: Update DocumentRoot
      lineinfile:
        path: /etc/apache2/sites-available/000-default.conf
        regexp: '^\s*DocumentRoot\s+'
        line: '    DocumentRoot {{ secure_directory_path }}'  # 변경할 안전한 경로
      when: document_root_check.stdout is search('htdocs') or
            document_root_check.stdout is search(default_document_root)
 
  handlers:
    - name: Restart Apache to apply changes
      service:
        name: apache2
        state: restarted