---
- name: Testing
  hosts: aws_server2
  gather_facts: no
  vars_files:
    - roles/mysql_security_checks/vars/main.yml
  tasks:
    - name: Include mysql_security_checks Testing
      import_tasks: roles/mysql_security_checks/tests/main.yml
