# 최상위 Testing_playbook.yml
---
- name: Testing
  hosts: aws_server2, aws_db
  gather_facts: no
  pre_tasks:
  - include_tasks: pre_tasks.yml
  vars_files:
    - roles/mysql_security_checks/vars/main.yml
  tasks:
    - name: Include mysql_security_checks Testing
      import_tasks: roles/mysql_security_checks/tests/Testing_tasks.yml
  
#- name: Testing
#  hosts: aws_server2, aws_web
#  gather_facts: no
#  pre_tasks:
#  - include_tasks: pre_tasks.yml
#  vars_files:
#    - roles/php_security_checks/vars/main.yml
#  tasks:
#    - name: Include php_security_checks Testing
#      import_tasks: roles/php_security_checks/tests/Testing_tasks.yml

