---
- name: os
  hosts: all
  tasks:
    - name: Print os family
      debug:
        msg: "the os fiamily is: {{ ansible_os_family }}"

    - name: Print os distribution
      debug:
        msg: "the os distribution is: {{ ansible_distribution }}"

    - name: Print os version
      debug:
        msg: "the os version is: {{ ansible_distribution_version }}"
