- name: Set vars for Debian
  include_vars: vars/vars_db.yml
  when: ansible_os_family == "Debian"

- name: Set vars for RedHat
  include_vars: vars/vars_rh.yml
  when: ansible_os_family == "RedHat"

- name: Testing tasks
  include_tasks: tests/testing_tasks_db.yml
  when: ansible_os_family == "Debian"

- name: Testing tasks
  include_tasks: tests/testing_tasks_rh.yml
  when: ansible_os_family == "RedHat"

- name: Include DB tasks
  include_tasks: tasks/main_db.yml
  when: ansible_os_family == "Debian"

- name: Include RH tasks
  include_tasks: tasks/main_rh.yml
  when: ansible_os_family == "RedHat"
